mkgif/urls.py
from django.urls import path
from . import views

app_name = 'mkgif'

urlpatterns = [
    path('', views.index, name='index'),
    path('details/<int:pk>/', views.details, name='details'),
    path('details/<int:pk>/edit', views.edit_name, name='edit_name')
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mkgif.urls')),
    path('accounts/', include('django.contrib.auth.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mkgif/models.py
from django.conf import settings
from django.db import models
from django.contrib.auth.models import User
import django_rq
from .utils import mk_gif_ffmpeg

# Create your models here.

class Animation(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)

    def enqueue(self, params):
        django_rq.enqueue(mk_gif_ffmpeg, {
            'pk': self.pk,
            'params': params,
            }
        )

    # Set how the model is displayed in the admins table
    def __str__(self):
        return(f"{self.name}")

class Image(models.Model):
    def image_path(self, filename):
        return f'{self.animation.pk}/{filename}'

    animation = models.ForeignKey('Animation', on_delete=models.CASCADE)
    image = models.ImageField(upload_to=image_path)

    def __str__(self):
        return(f"Animation: {self.animation}. Img: {self.image.name}")

mkgif/forms.py
from django.forms import ModelForm
from mkgif.models import Animation


class EditNameForm(ModelForm):
    class Meta:
        model = Animation
        fields = ('name',)

mkgif/views.py
from django.shortcuts import render, reverse
from .models import Animation, Image
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.conf import settings
from mkgif.forms import EditNameForm
import shutil

# Create your views here.

MEDIA_ROOT=settings.MEDIA_ROOT

@login_required
def index(request):
    if request.method == 'POST':
        anim = Animation.objects.create(name=request.POST['name'], user=request.user)
        for img in request.FILES.getlist('imgs'):
            Image.objects.create(animation=anim, image=img)
        anim.enqueue({})

    anims = Animation.objects.all()
    context = {
            'anims':anims
            }
    return render(request, 'mkgif/index.html', context)

@login_required
def details(request, pk):
    edit_name_form = None
    if request.method == 'DELETE':
        anim = get_object_or_404(Animation, pk=pk, user=request.user)
        shutil.rmtree(f"{MEDIA_ROOT}/{pk}")
        anim.delete()

        return HttpResponseRedirect(reverse('mkgif:index'))

    if request.method == 'POST':
        anim = Animation.objects.get(pk=pk)

        edit_name_form = EditNameForm(request.POST, instance=anim)
        if edit_name_form.is_valid():
            edit_name_form.save()
            edit_name_form = None
        return HttpResponseRedirect(reverse('mkgif:index'))

    anim = get_object_or_404(Animation, pk=pk, user=request.user)
    images = Image.objects.filter(animation=pk)
    context = {
            'anim': anim,
            'images' : images
            }

    print(context["images"][0])
    return render(request, 'mkgif/details.html' , context)

@login_required
def edit_name(request, pk):
    form = EditNameForm()
    context = {'form':form, "pk":pk}
    return render(request, "mkgif/partials/edit_name_form.html", context)

mkgif/templates/mkgif/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %} Make GIF {% endblock %}</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/holiday.css@0.9.8" />
        <script defer src="https://unpkg.com/htmx.org@1.9.5" integrity="sha384-xcuj3WpfgjlKF+FXhSQFQ0ZNr39ln+hwjN3npfM9VBnUskLolQAcN80McRIVOPuO" crossorigin="anonymous"></script>

    </head>
    <body hx-boost="true">
         <header>
             <h1>{% block header  %}Make GIF Animations {% endblock %}</h1>
        </header>
        <main>
            <nav>
    <ul>
        <li><a href="{% url 'mkgif:index' %}">Home</a></li>
        <li>
            <span>{{ user }}</span>
            <ul>
                <li><a href="{% url 'logout' %}">Logout</a></li>
            </ul>
            </span>
        </li>
    </ul>
</nav>
    {% block content %}
            <p>My GIF Animations:</p>
    {% endblock %}
        </main>

        <script >
                document.body.addEventListener('htmx:configRequest', (event) => {
                    event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
                })
        </script>
    </body>
</html>

mkgif/templates/mkgif/details.html
{% extends "mkgif/base.html" %}

{% load static %}

{% block title %} Anim {{anim.name}} {% endblock %}

{% block content %}
    <div> Gif sequence {{ anim.name }} {{anim.pk}}</div>
    </br>
    <ul class="img-list">
        {% for img in images %}
            <li><img src="{{img.image.url}}" width="200"  ></img>
            </li>
        {% endfor %}
        <div>
            <img src="{% get_media_prefix %}{{ anim.pk }}/out.gif" alt="gif">

           <!--   <a href="{% get_media_prefix  %}{{ anim.pk }}/out.gif" download ><button> Download GIF </button></a> -->
            </img>
        </div>
{% endblock %}≈

mkgif/templates/mkgif/index.html
{% extends "mkgif/base.html" %}

{% block title %} MkGIF Dev. {% endblock %}

{% block content %}


<h1> My Gif Animations </h1>
<table>

    {% for anim in anims %}
        <tr>
            <td>{{anim.pk}}</td>
            <td style="width:10rem"><a href="{% url 'mkgif:details' anim.pk %}">{{anim.name}}</a></td>

            <td>
                <button
                    data-hx-delete="{% url 'mkgif:details' anim.pk %}"
                    data-hx-trigger="click"
                    data-hx-target="closest tr"
                    data-hx-swap="delete"
                    >
                    Delete
                </button>
            </td>
            <td>
                <button
                    data-hx-get="{% url 'mkgif:edit_name' anim.pk %}"
                    data-hx-trigger="click"
                    data-hx-target="closest tr"
                    >
                    Edit Name
                </button>
            </td>
        </tr>
    {% endfor %}
</table>

<form action="{% url 'mkgif:index' %}" method="POST" enctype="multipart/form-data">
    <fieldset>
        <legend><label>Add New GIF Animation</label></fieldset>
        <input name="name" type="text" placeholder="Animation Name">
        <input name="imgs" type="file" multiple>
        <button>Submit</button>
    </fieldset>
</form>

{% endblock %}

mkgif/templates/mkgif/partials/edit_name_form.html
<td>
    {{pk}}
</td>
<td>
<form id="edit_name_form" style="display:flex;gap:1rem;" data-hx-target="body"
    data-hx-post="{% url 'mkgif:details' pk %}"
    >
    <input name="name" type="text">
</form>
</td>
<td>
    <button type="submit" form="edit_name_form"> Done </button>
</td>